require: rubocop-rspec
AllCops:
  Exclude:
    - 'wowza_rest.gemspec'
    - 'bin/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Exclude:
    - 'wowza_rest.gemspec'
    - 'spec/**/*'
Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
