---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 13 Jul 2017 17:12:00 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Www-Authenticate:
      - Digest realm="Wowza", domain="/", nonce="MTQ5OTk2NTkyMDYwOTozZjk1ZTczMzk3ZTFiNzVmNTY4YzdjNThhYmJiZjEwMw==",
        algorithm=MD5, qop="auth"
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"message":"The request requires user authentication","success":false,"code":"401","wowzaServer":"4.7.0"}'
    http_version: 
  recorded_at: Thu, 13 Jul 2017 17:12:00 GMT
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - Digest username="hazemt"
      - algorithm="MD5"
      - cnonce="1d1830c54e5c7e27106852cf8ff789db"
      - nc=00000001
      - nonce="MTQ5OTk2NTkyMDYwOTozZjk1ZTczMzk3ZTFiNzVmNTY4YzdjNThhYmJiZjEwMw=="
      - qop="auth"
      - realm="Wowza"
      - response="6df75ec122740cb7cb33d4af2dafb124"
      - uri="/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications"
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 13 Jul 2017 17:12:01 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"serverName":"_defaultServer_","applications":[{"id":"SMyApp","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/SMyApp","appType":null,"dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"dasdeqweq","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/dasdeqweq","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"heldlasdasd","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/heldlasdasd","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"heldlasdasddasdas","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/heldlasdasddasdas","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"helloworldapp","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/helloworldapp","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"myAppName","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/myAppName","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"my_app","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/my_app","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"my_new_app","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/my_new_app","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"my_new_apppp","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/my_new_apppp","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":false},{"id":"wowza","href":"/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/wowza","appType":"Live","dvrEnabled":false,"drmEnabled":false,"transcoderEnabled":false,"streamTargetsEnabled":true}]}'
    http_version: 
  recorded_at: Thu, 13 Jul 2017 17:12:01 GMT
recorded_with: VCR 3.0.3
